# Site settings
title: Igor T.'s Personal Log
email: legigor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Igor Tamashchuk's personal log.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tigp.name" # the base hostname & protocol for your site
twitter_username: legigor
github_username:  legigor

# Build settings
markdown: kramdown
